# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='url',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='IMDB link'),
        ),
    ]
